# Generated by Django 4.2.16 on 2024-11-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_type",
                    models.IntegerField(
                        help_text="0: Found, 1: Lost", verbose_name="Item Type"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        help_text="0: Pending, 1: In Progress, 2: Resolved",
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemsNameTag",
            fields=[
                ("item_name_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item_name",
                    models.CharField(
                        help_text="Stationery, clothing, electronic equipment, etc.",
                        max_length=100,
                        verbose_name="Name tags for items",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PickedOrDroppedLocationsTag",
            fields=[
                (
                    "PorD_location_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "picked_or_dropped_location_name",
                    models.CharField(
                        help_text="Name of the place where it was found or dropped, e.g., faculty building, student center, etc.",
                        max_length=100,
                        verbose_name="Location Name",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StorageLocationsTag",
            fields=[
                (
                    "storage_location_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "storage_location_name",
                    models.CharField(
                        help_text="Name of the place to store lost items, e.g., administrative office, library, etc.",
                        max_length=100,
                        verbose_name="Storage Location Name",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_path",
                    models.CharField(max_length=225, verbose_name="Image Path"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="top.item",
                        verbose_name="Item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="PorD_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="top.pickedordroppedlocationstag",
                verbose_name="Picked or Dropped Location",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="top.itemsnametag",
                verbose_name="Item Name",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="storage_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="top.storagelocationstag",
                verbose_name="Storage Location",
            ),
        ),
    ]
