# Generated by Django 4.2.16 on 2024-11-20 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("top", "0002_remove_itemimage_image_path_itemimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemimage",
            old_name="image",
            new_name="image_path",
        ),
    ]
