# Generated by Django 4.2.16 on 2024-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("top", "0003_rename_image_itemimage_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
