# Generated by Django 4.2.16 on 2024-12-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("top", "0004_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="storage_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="top.storagelocationstag",
                verbose_name="Storage Location",
            ),
        ),
    ]
