# Generated by Django 4.2.16 on 2024-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("top", "0005_alter_item_storage_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
